-- Run in Supabase SQL Editor: X (Twitter) draft copy for OpenClaw agent deliveries.

alter table public.stiri
  add column if not exists x_content text;

comment on column public.stiri.x_content is
  'Pre-formatted X/Twitter post or thread generated by OpenClaw; not shown on public site until editorial review.';
